-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "currentRun" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "interval" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "isDripFeed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "nextRunAt" TIMESTAMP(3),
ADD COLUMN     "runs" INTEGER NOT NULL DEFAULT 1;
