# (c) 2024-2026 Smmplan. All rights reserved.
FROM node:20-slim
WORKDIR /app

# The standalone output includes everything needed to run the app
COPY . .

# Environment variables for production
ENV NODE_ENV production
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Expose the default Next.js port
EXPOSE 3000

# Run the standalone server
CMD ["node", "server.js"]
